export const {
    PORT = 8080,
    SALT_ROUNDS = 10,
    SECRET_KEY = '',
    DATABASE_USER,
    DATABASE_PASSWORD,
    DATABASE_PORT,
    DATABASE_NAME,
    DATABASE_HOST,
    DATABASE_LOGGING
} = process.env
